version: '3.8'

services:
    app:
        build: .
        image: customers-api
        volumes:
            - .:/var/app
        restart: "no"
        command: rails server -p 3000 -b '0.0.0.0'
        ports:
            - 3000:3000
